name: ci

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Verify formatting
        if: ${{ github.event_name == 'pull_request' || github.ref_name == 'main' || github.ref_name == 'master' }}
        run: dart format --output=none --set-exit-if-changed .
      - name: Static analysis
        run: dart analyze
      - name: Run tests
        if: ${{ github.event_name == 'pull_request' || github.ref_name == 'main' || github.ref_name == 'master' }}
        run: dart test
      - name: Generate API docs
        if: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master') }}
        run: dart doc
